package org.circuit.method;

public enum Method {
	RANDOM_ENRICH,
	BETTER_RANDOM_ENRICH,
	CIRCUITS_SCRABLE,
	SCRAMBLE_WITH_NEW_RANDOM,
	RANDOM_CIRCUIT,
	RANDOM_FROM_DATABASE,
	BETTER_FROM_DATABASE;
}
